name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.9.0
    - name: Build
      run: |
        npm install && npm run build
    - name: Cp File
      run: cp -r .asf.yaml build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: asf-site
        PUBLISH_DIR: ./build
