name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.0
    - name: Build
      run: |
        mkdir dist && npm install && npm i docsite && node_modules/docsite/bin/docsite.js build
    - name: Cp File
      run: cp -r docs/zh-cn/* ./zh-cn/docs && cp -r docs/en-us/* ./en-us/docs && cp -r 404.html .asf.yaml index.html en-us zh-cn build img docs dist/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: asf-site
        PUBLISH_DIR: ./dist
